import traceback


try:
    a= 10
    print(b)

except Exception as e:
    traceback.print_exec()